momentohq/client-sdk-php

src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Errors/Errors.php
src/Cache/_ScsControlClient.php
src/Cache/_ScsDataClient.php
src/Utilities/_ErrorConverter.php
tests/Cache/CacheClientTest.php

Update error handing to conform to client SDK spec. Uses `isXXX()` methods such as `asHit`, `asError`, etc. to provide type-safe instances and informative IDE code completion.

feat: improved error UX

---

src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/SimpleCacheClient.php
src/Cache/_ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Adds the remaining list API operations: pop front, pop back, length, and erase. Also adds `__toString()` in the response base class and overrides the base implementation in the response subtypes that hold data.

feat: adding list API continued

---

src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/SimpleCacheClient.php
src/Cache/_ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Added dictionary set, get, and delete APIs and tests to check those operations.
Ticket: #17

chore: add dictionary set, get, delete

---

tests/Cache/CacheClientTest.php

integration test assertions are currently missing all details in
the most expected case: When they got an error back.
This change makes tests output more helpful & verbose failures.
Replaces assertion messages like:
```
8) Momento\Tests\Cache\CacheClientTest::testListPushFrontFetchHappyPath
Failed asserting that null is not null.
/Users/kenny/gits/client-sdk-php/tests/Cache/CacheClientTest.php:427
9) Momento\Tests\Cache\CacheClientTest::testListPushFront_TruncateList
Failed asserting that null is not null.
/Users/kenny/gits/client-sdk-php/tests/Cache/CacheClientTest.php:480
```
With something a little more like:
```
35) Momento\Tests\Cache\CacheClientTest::testListPushBack_NoRefreshTtl
Failed asserting that Momento\Cache\CacheOperationTypes\CacheListFetchResponseError Object …
```

chore: fix test assertions

---

README.ja.md
README.template.md
composer.json
src/Auth/AuthUtils.php
src/Auth/EnvMomentoTokenProvider.php
src/Auth/ICredentialProvider.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Errors/Errors.php
src/Cache/SimpleCacheClient.php
src/Cache/_ControlGrpcManager.php
src/Cache/_DataGrpcManager.php
src/Cache/_ScsControlClient.php
src/Cache/_ScsDataClient.php
src/Utilities/_DataValidation.php
src/Utilities/_ErrorConverter.php
tests/Cache/CacheClientTest.php

Adds `declare(strict_types=1)` to each file to enable strict typing throughout the SDK. Also bumps our minimum PHP version requirement to 8.0+ and cleans up the timeout calculation in the data client.
Addresses issue #41

feat: using strict types

---

src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Psr16CacheClient.php
tests/Cache/CacheClientTest.php

Updated all value accessors with `value<type>`. 
For example, `valueString` and `valueInt`. 
As commented [here](https://github.com/momentohq/client-sdk-php/issues/48#issuecomment-1311988727), I think we can close #48. (I'm mentioning it here since I was going to address this issue in this PR along with #47).
Closes #47

chore: prefix all value accessors with `value<type>`

---

src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/_ScsDataClient.php
tests/Cache/CacheClientTest.php

Added `fieldValueDictionary` accessor to `dictionaryGetBatch` to return an array of field/value pairs.
Also, updated `dictionary` accessor to `fieldValueDictionary` for `dictionaryFetch` to be consistent with naming.
Corresponding tests are also updated.
Closes #53

chore:  add `fieldValueDictionary` accessor to `dictionaryGetBatch` 

---

src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/SimpleCacheClient.php
src/Cache/_ScsDataClient.php
tests/Cache/CacheClientTest.php

Received feedback from @malandis on this PR to implement `flush` in `laravel-cache` that it'll give better performance to use `setDelete` after "batch" delete keys from a cache. ([link](https://github.com/momentohq/laravel-cache/pull/12#discussion_r1025902176))
With that, added `setDelete` and tests so it can be used in `laravel-cache` to address the feedback.
Closes #69

chore: add `setDelete`

---

src/Cache/SimpleCacheClient.php
src/Cache/_ScsDataClient.php
src/Requests/CollectionTtl.php
tests/Cache/CacheClientTest.php

- Made `$refreshTtl` optional and default to `true`.
- re-ordered arguments for list push and dictionary increment operations so that `$trunncateFrontToSie`, `$truncateBackToSize`, and `amount` are before `$refreshTtl`.
- updated the tests to reflect the above changes.
This PR needs to get merged before working on #54.
Closes #49 
Closes #50

chore: make `$refreshTtl` optional and re-order arguments for list push and dictionary increment 

---

CONTRIBUTING.md
Dockerfile
dev-docker-build.sh
dev-run-integration-tests.sh
examples/README.md
examples/dev-php-docker-shell.sh
examples/dictionary-example.php

This commit changes the Dockerfile so that we can use a bind mount
to mount the local dir, rather than having to copy all the files
into the image at build time.
This should allow us to re-use this docker image for other purposes;
in the near future we can push it to an ECR repo so that devs
don't have to build it locally at all.

feat: make Dockerfile more general-purpose

---

.editorconfig

I noticed [a recent PR had stray changes trimming trailing whitespace](https://github.com/momentohq/client-sdk-php/pull/70/files). This makes it a little harder to follow.
An [EditorConfig](https://editorconfig.org/) file specifies basic editor configuration for the project, like trimming trailing whitespace. [Most editors support it automatically](https://editorconfig.org/#pre-installed) and for the rest [there is a plugin](https://editorconfig.org/#download). It doesn't hurt, and avoids those little whitespace nits.

style: Add an EditorConfig file.

---

src/Auth/StringMomentoTokenProvider.php

I'm getting [deprecation warnings](https://www.php.net/manual/en/migration82.deprecated.php) with PHP 8.2 because the `StringMomentoTokenProvider` properties aren't declared in the class. This commit declares the properties.

fix: declare string provider properties

---

composer.lock
examples/README.md
examples/composer.json
examples/dictionary-example.php
examples/example.php
examples/list-example.php
examples/loadgen.php
examples/psr16-example.php

This commit removes the `repositories` section from `composer.json` as we are now listed on [packagist](https://packagist.org/packages/momentohq/client-sdk-php). We also update examples to generate their own temporary cache names instead of requiring an environment variable and delete the generated caches at the end of the examples. Finally, we correct some errors due to our examples not using `CollectionTtl`.

fix: update composer files and examples for latest SDK version

---

src/Cache/CacheClient.php
src/Cache/Internal/ScsDataClient.php
src/Utilities/_DataValidation.php

This commit renames `items` to `elements` for `dictionarySetFields` to conform to naming conventions. It also removes an unused validator function.

fix: rename items to elements

---

src/Auth/AuthUtils.php
src/Auth/EnvMomentoTokenProvider.php
src/Auth/StringMomentoTokenProvider.php
tests/Cache/MomentoTokenProviderTest.php

This commit adds support for V1 auth tokens.

feat: add support for V1 auth tokens

---

src/Cache/Internal/DataGrpcManager.php
src/Cache/Internal/IdleDataClientWrapper.php
src/Cache/Internal/ScsDataClient.php

Prior to this commit we didn't ever have an explicit call to close
the gRPC channel; in cases where we are cycling the client out
due to reaching the idle timeout, this could leave open sockets /
file descriptors behind.  This commit updates the code to explicitly
close the channel when replacing the client.

fix: explicitly close gRPC channel when cycling idle client

---

src/Auth/EnvMomentoTokenProvider.php
tests/Cache/CacheClientTest.php
tests/Cache/MomentoTokenProviderTest.php

This commit changes our token provider code to use $_SERVER
instead of `getenv`. `getenv` is not threadsafe and can cause
security issues.

fix: use $_SERVER instead of getenv

---

src/Cache/CacheClient.php
src/Config/Configuration.php
src/Config/Configurations/Laptop.php
src/Config/IConfiguration.php
src/Config/Transport/IGrpcConfiguration.php
src/Config/Transport/ITransportStrategy.php
src/Config/Transport/StaticGrpcConfiguration.php
src/Config/Transport/StaticTransportStrategy.php
tests/Cache/CacheClientTest.php
tests/Cache/Psr16ClientTest.php

For users who may end up with over 100 concurrent requests in flight,
we need to be able to support multiple gRPC channels. This commit adds
a configuration setting to allow users to specify the desired number
of channels.
This most likely won't doing anything useful until we add the config
flag to disable persistent TCP connections in the gRPC channel
constructor, because we will just end up re-using the same channel
multiple times.

feat: add configurability for number of gRPC channels

---

src/Cache/Psr16CacheClient.php

This PR continues #162:
"I have adjusted these methods to perform up to 100 operations concurrently against the cache, and where there are more than 100 operations to do, it performs the first 100, then the next 100, etc. This also fixes a bug where it is attempted to iterate the keys more than once. An iterable in PHP need not implement the ability to rewind, so we must only iterate once."

feat: Improve PSR cache multiple operation performance

---

src/Cache/CacheClient.php
src/Cache/Internal/ControlGrpcManager.php
src/Cache/Internal/IdleDataClientWrapper.php
src/Cache/Internal/ScsControlClient.php
tests/Cache/CacheClientTest.php

This is intended to help us determine whether or not a persistent gRPC connection that gets into a bad state can be explicitly closed and re-opened to restore the environment to a healthy state.

feat: add `close` method for explicitly closing client

---

.github/workflows/on-pull-request.yaml
.github/workflows/on-push-to-main.yaml
.github/workflows/on-push-to-release.yaml
CONTRIBUTING.md
dev-run-integration-tests.sh
tests/Cache/CacheClientTest.php
tests/Cache/MomentoTokenProviderTest.php
tests/Cache/Psr16ClientTest.php
tests/Storage/StorageClientTest.php

just fixes a few straggling places where we hadn't finished this
env var rename.

chore: rename TEST_AUTH_TOKEN to MOMENTO_API_KEY

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
Makefile

We add a devcontainer and Dockerfile to do local develpoment in
IntelliJ. We also add a Makefile wtih the common dev targets.
To use in IntelliJ:
- Under services, add Docker
- Open the devcontainer.json in the project
- Right click the blue wireframe square in the gutter by the opening curly
Select "Create container and mount sources..."; select IntelliJ IDEA.
- Wait for it to download IntelliJ, build, and launch
- Develop in the new remote container IDE
- Use settings sync to get settings aligned between the host IntelliJ and guest

chore: support devcontainer development

---

.github/workflows/on-pull-request.yaml

Try caching the PHP extensions since they take a long time to
build. We try this both in the lint job and test job.
We also temporarily reduce the number of versions under test in
order to increase velocity.

ci: cache extensions

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
tests/Cache/CacheClientTest.php

- add `sortedSetRemoveElement` api
- add integ tests
https://github.com/momentohq/client-sdk-php/issues/213

feat: add sortedSetRemoveElement api

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
tests/Cache/CacheClientTest.php

We add placeholders for future work to avoid clobbering each other in
upcoming PRs.
When writing new features, replace the placeholder comment with the
new code.

chore: add placeholders to avoid future merge conflicts

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Adds the sorted set remove elements api, documentation, response
types, and integration tests.

feat: add sorted set remove elements

---

src/Cache/CacheOperationTypes/CacheOperationTypes.php

When trying to use the SortedFetchHit response in the drop-in client, I get this error:
```
Error : Typed property Momento\Cache\CacheOperationTypes\SortedSetFetchHit::$elements must not be accessed before initialization
```
This commit is an attempt to fix that error message.

fix: initializing typed property  in sortedSetFetchHit

---

src/Cache/CacheClient.php

The previous PR for sorted set increment score contained a typo in a
docstring.

chore: fix inconsistent comment

---

src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Stop using is_string() for validation as it fails for strings that have automatically been converted into integers when used as keys in associative arrays.
Update isNullOrEmpty to check if the given value is a scalar (a string, int, float, or bool) and then check if its string value is empty instead of explicitly taking a string.
Remove a dictionary set fields test case that checks for an error when given this array: [""]. PHP will implicitly treat it as this associative array: [0 => ""], which is valid with our new validation. We need to choose whether to support integer string keys or whether to be able to reject this specific type of invalid input.

fix: stop using is_string() for validation

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
tests/Cache/CacheClientTest.php

Add the sorted set length by score API, integration tests, and documentation.

feat: add sortedSetLengthByScore

---

src/Cache/CacheClient.php
src/Cache/Internal/ScsDataClient.php

change the order argument in the sorted set functions to explicitly take SORT_ASC and SORT_DESC, and treat other values as ascending. This replaces the previous logic where SORT_DESC or lower was descending, and SORT_ASC or higher was ascending. Using built-in constants in a comparison was confusing.

chore: make order in the sorted set functions more explicit

---

src/Cache/CacheClient.php
src/Cache/Internal/ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Add $inclusiveMin and $inclusiveMax to sortedSetFetchByScore to allow callers to toggle whether the min and max scores should be inclusive or exclusive. They default to inclusive.
Add tests for the flags.
Change the behavior for an unrecognized sort order from defaulting to ascending to returning an error.
Make $order not nullable. There isn't a reason for it to be null and it has a default argument.

feat: add flags for toggling inclusivity on fetchByScore scores

---

tests/Cache/CacheClientTest.php

Rename the tests that are named ThrowsException to ReturnsError, since none of them test a condition that throws an exception.

chore: rename the ThrowsException tests to ReturnsError

---

CONTRIBUTING.md
README-logging.md
README-proxying.md
README.template.md

Replace language like "Momento PHP SDK" with "Momento SDK for PHP".
Add an attribution section to the README template with the required attribution statement.
Remove logo links from logging and proxying READMEs that don't render correctly on
github.

chore: Update the documentation comply with the PHP license

---

src/Cache/CacheClient.php
src/Cache/Internal/ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Remove the type that the score arguments use in sorted set methods. When they were explicitly float, it was an error to pass in an int score. They are now defined as float|int, but are left untyped in the functions because union types are unsupported in the oldest versions of PHP we support.
Update data validation to handle the new potential score types.
Rearrange the arguments of sorted set functions that take a score range to put the min/max scores and min/max inclusive flags next to each other instead of interleaving them.

chore: remove the type from sorted set scores so they support ints

---

examples/composer.json
examples/sorted-set-example.php

- Update the composer.json to reference the `main` branch of `client-sdk-php` repo since we currently do not have a released sdk version that contains the sorted-set apis
- Add sorted-set examples
https://github.com/momentohq/client-sdk-php/issues/213
https://github.com/momentohq/dev-eco-issue-tracker/issues/1033

feat: add sorted-set examples

---

.github/workflows/on-pull-request.yaml

Previously we limited the versions under test to 7.4 and 8.4 for
expediency. We revert that change to test versions {8.0, ..., 8.3} as
well.

ci: revert to test over versions {7.4, ..., 8.4}

---

src/Cache/Interceptors/ReadConcernInterceptor.php
src/Cache/Internal/DataGrpcManager.php
src/Config/Configuration.php
src/Config/Configurations/InRegion.php
src/Config/Configurations/Laptop.php
src/Config/IConfiguration.php
src/Config/ReadConcern.php
tests/Cache/CacheClientTest.php

Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1055 
Adds the `read-concern` header with `BALANCED` and `CONSISTENT` options to the cache configs.
Tested manually and added a test case for ensuring the read concern header can be overridden. 
Also switched the cache test client to use the consistent header to match the JS sdk, but can revert that if not needed here.

feat: add ReadConcern config

---

src/Cache/Errors/Errors.php
src/Utilities/_ErrorConverter.php

Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1042
When a RESOURCE_EXHAUSTED error is received, we now parse the err metadata in order to report the cause in the message wrapper. If the metadata is not available, we try to use string matching on the error details.

chore: improve resource exhausted error message

---

src/Cache/Internal/ControlGrpcManager.php
src/Cache/Internal/DataGrpcManager.php

- Based on the commit [here](https://github.com/googleapis/gax-php/pull/240/files), dynamic txt lookup for dns resolution flag is disabled by default in grpc-php. 
- This commit explicitly disables it too.
```
tcpdump: listening on any, link-type PKTAP (Apple DLT_PKTAP), snapshot length 524288 bytes
pd1nsc3.st.vc.shawcable.net.domain > 10.0.0.249.57231: [udp sum ok] 2987 q: A? control.cell-alpha-dev.preprod.a.momentohq.com. 2/0/0 control.cell-alpha-dev.preprod.a.momentohq.com. [5m] CNAME cache.cell-alpha-dev.preprod.a.momentohq.com., cache.cell-alpha-dev.preprod.a.momentohq.com. [1m] A 54.186.170.81 (100)
pd1nsc3.st.vc.shawcable.net.domain > 10.0.0.249.61836: [udp sum ok] 39756 q: AAAA? control.cell-alpha-dev.preprod.a.momentohq.com. 1/1/0 control.cell-alpha-dev.preprod.a.momentohq.com. …
```

fix: disable dynamic DNS service config

---

src/Cache/Internal/ScsDataClient.php
tests/Cache/CacheClientTest.php

This commit adds a number of integration tests for the sorted set union store API. It also corrects the handling of the aggregate function when users explicitly pass in `null` for that argument. The PHP Redis client library is **not** affected by the existing SDK logic because it validates the correctness of the aggregate function arguments before making any SDK calls.

chore: adding more testing for sorted set union store
