momentohq/client-sdk-php

src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/SimpleCacheClient.php
src/Cache/_ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Added tests and fixed some issues they uncovered.

fix: add tests and fix bugs

---

.github/workflows/on-push-to-main.yaml

This fixes an error in the push-to-main github action.

fix: remove offending action

---

README.template.md
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/SimpleCacheClient.php
src/Cache/_ScsDataClient.php
tests/Cache/CacheClientTest.php

Adds push front, push back, and fetch operations.

feat: adding list API

---

examples/README.md
examples/dictionary-example.php
examples/example.php
examples/list-example.php

- Added list and dictionary examples
- Updated simple example
- Updated README
Ran on ap-northeast-1
Running `example.php`
```
******************************************************************
*                      Momento Example Start                     *
******************************************************************
Cache example-tokyo already exists.
SUCCESS: List caches: example-tokyo	php-integration-tests
Setting key: MyKey to value: MyValue
SUCCESS: - Set key: MyKey value: MyValue cache: example-tokyo
Getting value for key: MyKey
SUCCESS: - Get key: MyKey value: MyValue cache: example-tokyo
******************************************************************
*                       Momento Example End                      *
```
Running `list-example.php`
``` …
```

chore: add list/dictionary examples

---

src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/SimpleCacheClient.php
src/Cache/_ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Added dictionary fetch, getbatch, setbatch APIs along with tests for those.
Ticket #17

chore: add dictionary fetch getbatch setbatch

---

composer.json
composer.lock
src/Auth/AuthUtils.php
src/Auth/EnvMomentoTokenProvider.php

Replaces the base64 token decoding with an actual JWT library.

chore: add Firebase JWT

---

composer.lock
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/SimpleCacheClient.php
src/Cache/_ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

We need to add `setAdd` and `setFetch` to implement TaggedCache in Laravel. (`setFetch` is more to test `setAdd` is correctly implemented)

chore: add `setAdd` and `setFetch`

---

.github/workflows/qodana.yml

Microsoft(githubs) codeql scan tool doesnt support php so want to give qodana a try from jet brains. Maybe we can switch to this for all the repos longer term since seems to have nice IDE intergrations. Trying to get a feel for it and provide some coverage for php sdk.

chore: try out qodana for php code scan

---

.github/workflows/qodana.yml

Attempting to fix the CI failures related to outdated qodana package.

chore: update qodana

---

examples/composer.json
examples/index-loadgen.php

SDK version `0.4.0` -> `0.6.0` in `examples`

chore: update SDK version in examples

---

composer.json

This commit adds extra metadata to `composer.json` in anticipation of listing the SDK with [packagist](https://packagist.org/).

chore: update composer.json for packagist listing

---

src/Cache/CacheClient.php
src/Cache/Internal/ControlGrpcManager.php
src/Cache/Internal/DataGrpcManager.php
src/Cache/Internal/ScsControlClient.php
src/Cache/Internal/ScsDataClient.php

This commit moves internal classes into their own namespace.

fix: move internal classes to an internal namespace

---

src/Cache/CacheClient.php
src/Cache/Internal/IdleDataClientWrapper.php
src/Config/Configurations/InRegion.php
src/Config/Configurations/Laptop.php
src/Config/Transport/ITransportStrategy.php
src/Config/Transport/StaticTransportStrategy.php

This commit adds support for an idle client timeout to address the issue of dropped connections in lambda environments.

feat: add idle data client wrapper

---

composer.json
composer.lock
src/Logging/LoggerFactoryBase.php
src/Logging/NullLoggerFactory.php
src/Logging/PassthroughLoggerFactory.php

This commit adds support for v3 of the psr/log PHP logging interface as well as a bit of miscellaneous code cleanup.

chore: add support for psr/log v3

---

.github/dependabot.yml
.github/workflows/on-pull-request.yaml
README.ja.md
examples/README.md
examples/composer.json
examples/dictionary-example.php
examples/list-example.php
examples/set-example.php

This commit updates the examples to use the latest SDK version and fills in testing/CI gaps by hooking up dependabot and running example scripts as part of CI.

chore: update examples for SDK v1.2.0

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

This PR just adds a commit to #149 , renaming from `SetUnion` to `SetAddElements` for consistency with our other SDKs.
thanks for the contribution, Graham!

feat: add SetAddElements API

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php

This PR is a continuation of #154 
- feat: Implement async cache client methods
- fix: Fixed typos in `setAddElements`

feat: async client

---

src/Config/Configurations/InRegion.php

This PR is a continuation of #161.

fix: Correct broken InRegion configuration

---

composer.json
src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
tests/Cache/CacheClientTest.php

This commit adds the `SetIf` operations to the SDK and deprecates `SetIfNotExists` in favor of `SetIfAbsent`. It also cleans up the formatting of code samples in doc comments for better readability in IDEs.

feat: add SetIf operations

---

src/Cache/Interceptors/AgentInterceptor.php
src/Cache/Internal/ControlGrpcManager.php
src/Cache/Internal/DataGrpcManager.php
src/Storage/Internal/StorageGrpcManager.php

https://github.com/momentohq/dev-eco-issue-tracker/issues/894

feat: one time headers

---

.github/workflows/on-pull-request.yaml
.github/workflows/on-push-to-main.yaml
.github/workflows/on-push-to-release.yaml
CONTRIBUTING.md
README-logging.md
README-proxying.md
README.ja.md
README.md
examples/README.md
examples/composer.json
examples/dictionary-example.php
examples/doc-example-files/storage-cheat-sheet.php
examples/doc-examples-php-apis.php
examples/example.php
examples/index-loadgen.php
examples/list-example.php
examples/psr16-example.php
examples/readme.php
examples/set-example.php
examples/storage-example.php

This commit adds API snippets to the docs example. They will be consumed by our public dev docs, which will be updated in another PR in that repository.

chore: add storage docs snippets

---

LICENSE

Adds the Apache 2.0 license to the project.

chore: add Apache 2.0 license

---

.github/workflows/dependency-review.yml
.github/workflows/on-pull-request.yaml
.github/workflows/on-push-to-main.yaml
.github/workflows/on-push-to-release.yaml
.github/workflows/qodana.yml
.gitignore
.php-cs-fixer.dist.php
composer.json
composer.lock
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Utilities/_DataValidation.php

copy of #210 , rebased onto main

chore: Run CI on PHP 8.3 and 8.4, fix PHP 8.4 support, pin actions versions

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
tests/Cache/CacheClientTest.php

- Add `itemGetTtl` API
- Add integration test

feat: add getItemTtl api

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
tests/Cache/CacheClientTest.php

- Add update ttl apis:
- `increaseTtl`
- `decreaseTtl`
- `updateTtl`
- Add integ tests

feat: add update ttl apis

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php

https://github.com/momentohq/client-sdk-php/issues/213

fix: doc strings

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
tests/Cache/CacheClientTest.php

Adds the sortedSetGetScore method, response type, and tests to the
client.

feat: add sortedSetGetScore

---

src/Cache/CacheClient.php
tests/Cache/CacheClientTest.php

Adds additional tests for sortedSetRemoveElement and tweaks
documentation.

test: add more tests for sorted set remove element

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Add validation for an array of sorted set elements.
Add tests for sortedSetPutElements.

feat: add sortedSetPutElements

---

src/Cache/CacheClient.php

Documentation tweak for singular vs plural.

chore: correct `sorted set remove elements` mention in docstrings

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
tests/Cache/CacheClientTest.php

Adds the sorted set increment score API, response types, integration
tests, and documentation.

feat: add sorted set increment score

---

src/Cache/CacheClient.php
src/Cache/CacheOperationTypes/CacheOperationTypes.php
src/Cache/Internal/ScsDataClient.php
src/Utilities/_DataValidation.php
tests/Cache/CacheClientTest.php

Add the sorted set fetch by score API, response types, integration tests, and documentation.

feat: add sortedSetFetchByScore

---

tests/Cache/CacheClientTest.php

Remove tests based on throwing TypeError. They were the cause of the errors/warnings in IntelliJ and test the PHP type system rather than Momento validation code. A momento function argument that isn't nullable throws a TypeError when given null.
Remove tests based on casting null to string. (string)null is equal to empty string, so those tests were redundant.
Change some of the existing TypeError tests to test empty strings instead of nulls to test the validation logic for those fields.
Fix two ttl assertions that weren't checking the returned values.
Fix misc. warnings, including unused variables, and extra arguments from copy/paste errors.

chore: remove unnecessary tests and fix test warnings

---

.devcontainer/devcontainer.json
CONTRIBUTING.md

- Add development using dev-container documentation in contributing.md file
https://github.com/momentohq/dev-eco-issue-tracker/issues/1033

feat: add dev-container documentation

---

src/Config/Configuration.php
src/Config/IConfiguration.php
src/Config/Transport/IGrpcConfiguration.php
src/Config/Transport/ITransportStrategy.php

Pass the read concern config option when using the with... methods.
Add docs warning that configuration interfaces will change if options are added.

fix: correct small issues with the configurations.
